services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: rails-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql2://root:password@db:3306/app_development
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: rails-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: